# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{meac_control}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernd Ahlers"]
  s.date = %q{2010-01-16}
  s.description = %q{Library to communicate with a Mitsubishi Electric G-50A centralized controller}
  s.email = %q{bernd@tuneafish.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "lib/meac_control.rb",
     "lib/meac_control/command.rb",
     "lib/meac_control/command/drive.rb",
     "lib/meac_control/command/fan_speed.rb",
     "lib/meac_control/command/generic.rb",
     "lib/meac_control/device.rb",
     "lib/meac_control/http.rb",
     "lib/meac_control/xml.rb",
     "lib/meac_control/xml/abstract_request.rb",
     "lib/meac_control/xml/exceptions.rb",
     "lib/meac_control/xml/get_request.rb",
     "lib/meac_control/xml/response.rb",
     "lib/meac_control/xml/set_request.rb",
     "spec/fixtures/get-request.xml",
     "spec/fixtures/get-response-error.xml",
     "spec/fixtures/get-response-ok.xml",
     "spec/fixtures/set-request.xml",
     "spec/lib/meac_control/command/drive_spec.rb",
     "spec/lib/meac_control/command/fan_speed_spec.rb",
     "spec/lib/meac_control/command/generic_spec.rb",
     "spec/lib/meac_control/device_spec.rb",
     "spec/lib/meac_control/http_spec.rb",
     "spec/lib/meac_control/xml/abstract_request_spec.rb",
     "spec/lib/meac_control/xml/get_request_spec.rb",
     "spec/lib/meac_control/xml/response_spec.rb",
     "spec/lib/meac_control/xml/set_request_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/shared_examples.rb"
  ]
  s.homepage = %q{http://github.com/bernd/meac_control}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Library to communicate with a Mitsubishi Electric G-50A centralized controller}
  s.test_files = [
    "spec/lib/meac_control/command/drive_spec.rb",
     "spec/lib/meac_control/command/fan_speed_spec.rb",
     "spec/lib/meac_control/command/generic_spec.rb",
     "spec/lib/meac_control/http_spec.rb",
     "spec/lib/meac_control/device_spec.rb",
     "spec/lib/meac_control/xml/get_request_spec.rb",
     "spec/lib/meac_control/xml/set_request_spec.rb",
     "spec/lib/meac_control/xml/abstract_request_spec.rb",
     "spec/lib/meac_control/xml/response_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/shared_examples.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<httpclient>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<httpclient>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

